import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Navbar } from '../components/Navbar';
import { Subject } from '../types';
import '../styles/App.css';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

export function AddCoursePage() {
  const navigate = useNavigate();
  const [saving, setSaving] = useState(false);
  const [isCustomCategory, setIsCustomCategory] = useState(false);
  
  const [formData, setFormData] = useState({
    name: '',
    categoryId: '12th',
    customCategory: '',
    description: '',
    banner: '',
    color: '#3b82f6'
  });

  const handleInputChange = (field: string, value: string) => {
    setFormData({ ...formData, [field]: value });
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setFormData({ ...formData, banner: reader.result as string });
      };
      reader.readAsDataURL(file);
    }
  };

  const generateUniqueId = (name: string): string => {
    const timestamp = Date.now();
    const randomStr = Math.random().toString(36).substring(2, 7);
    const baseName = name.toLowerCase().replace(/[^a-z0-9]/g, '-').substring(0, 20);
    return `${baseName}-${timestamp}-${randomStr}`;
  };

  const handleSubmit = async () => {
    // Validation
    if (!formData.name || !formData.description) {
      alert('Please fill in course name and description');
      return;
    }

    if (isCustomCategory && !formData.customCategory) {
      alert('Please enter a custom category name');
      return;
    }

    const categoryToUse = isCustomCategory ? formData.customCategory : formData.categoryId;
    const autoGeneratedId = generateUniqueId(formData.name);

    const newSubject: Subject = {
      id: autoGeneratedId,
      name: formData.name,
      description: formData.description,
      icon: '', // Empty icon field
      color: formData.color,
      banner: formData.banner || undefined,
      contentTypes: []
    };

    try {
      setSaving(true);
      const response = await fetch(`${API_BASE_URL}/categories/${categoryToUse}/subject`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(newSubject)
      });

      if (!response.ok) throw new Error('Failed to create course');

      alert('Course created successfully!');
      navigate(`/edit-content/${categoryToUse}/${autoGeneratedId}`);
    } catch (err) {
      console.error('Error:', err);
      alert('Failed to create course. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const handleCancel = () => {
    if (window.confirm('Cancel creating new course?')) {
      navigate('/manage-courses');
    }
  };

  return (
    <>
      <Navbar />
      <div className="container">
        <div className="page-header">
          <h1 className="page-title">Add New Course</h1>
        </div>

        <div className="content-form">
          <h2 style={{ marginBottom: '1.5rem' }}>Course Information</h2>

          <div className="form-group">
            <label className="form-label">Course Name *</label>
            <input
              type="text"
              className="form-input"
              value={formData.name}
              onChange={(e) => handleInputChange('name', e.target.value)}
              placeholder="e.g., Physics"
            />
            <small style={{ color: '#666', fontSize: '0.85rem' }}>
              A unique ID will be automatically generated
            </small>
          </div>

          <div className="form-group">
            <label className="form-label">Category *</label>
            <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.5rem' }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <input
                  type="radio"
                  checked={!isCustomCategory}
                  onChange={() => setIsCustomCategory(false)}
                />
                Predefined Category
              </label>
              <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <input
                  type="radio"
                  checked={isCustomCategory}
                  onChange={() => setIsCustomCategory(true)}
                />
                Custom Category
              </label>
            </div>
            
            {!isCustomCategory ? (
              <select
                className="form-select"
                value={formData.categoryId}
                onChange={(e) => handleInputChange('categoryId', e.target.value)}
              >
                <option value="12th">12th Grade</option>
                <option value="11th">11th Grade</option>
                <option value="10th">10th Grade</option>
              </select>
            ) : (
              <input
                type="text"
                className="form-input"
                value={formData.customCategory}
                onChange={(e) => handleInputChange('customCategory', e.target.value)}
                placeholder="Enter custom category name (e.g., 9th Grade, College, Professional)"
              />
            )}
          </div>

          <div className="form-group">
            <label className="form-label">Description *</label>
            <textarea
              className="form-textarea"
              value={formData.description}
              onChange={(e) => handleInputChange('description', e.target.value)}
              placeholder="Brief description of the course"
            />
          </div>

          <div className="form-group">
            <label className="form-label">Color *</label>
            <div className="color-picker-wrapper">
              <input
                type="color"
                className="color-input"
                value={formData.color}
                onChange={(e) => handleInputChange('color', e.target.value)}
              />
              <input
                type="text"
                className="form-input"
                value={formData.color}
                onChange={(e) => handleInputChange('color', e.target.value)}
                placeholder="#3b82f6"
                style={{ flex: 1 }}
              />
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Course Image (Optional)</label>
            <div className="image-upload" onClick={() => document.getElementById('banner-upload')?.click()}>
              {formData.banner ? (
                <img src={formData.banner} alt="Course image preview" className="image-preview" />
              ) : (
                <div>
                  <p>Click to upload course image</p>
                  <p style={{ fontSize: '0.85rem', color: '#666', marginTop: '0.5rem' }}>
                    Recommended: 1200x400px or any banner size
                  </p>
                </div>
              )}
            </div>
            <input
              id="banner-upload"
              type="file"
              accept="image/*"
              style={{ display: 'none' }}
              onChange={handleImageUpload}
            />
          </div>

          <div className="form-actions">
            <button className="btn btn-secondary btn-small" onClick={handleCancel}>
              Cancel
            </button>
            <button 
              className="btn btn-success btn-small" 
              onClick={handleSubmit}
              disabled={saving}
            >
              {saving ? 'Creating...' : 'Create Course'}
            </button>
          </div>

          <div style={{ marginTop: '2rem', padding: '1rem', background: '#e0f2fe', borderRadius: '8px' }}>
            <strong>ℹ️ Next Steps:</strong>
            <p style={{ marginTop: '0.5rem', color: '#666' }}>
              After creating the course, you'll be taken to the content editor where you can:
            </p>
            <ul style={{ marginTop: '0.5rem', marginLeft: '1.5rem', color: '#666' }}>
              <li>Add content types (Notes, Videos, Mock Tests, etc.)</li>
              <li>Create topics and subtopics</li>
              <li>Add actual content to each topic</li>
            </ul>
          </div>
        </div>
      </div>
    </>
  );
}